name: CMake

on:
  push: { }
  pull_request: { }
  schedule:
    - cron: '30 4 * * 1'
  workflow_dispatch: { }

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, windows-2019, ubuntu-latest ]
        build-type: [ Release ]
        cxx-standard: [ 11, 14, 17, 20 ]
        warning-as-errors: [ OFF ]

        include:
          - os: ubuntu-latest
            generator: -G Ninja
            setup: |
              sudo apt update
              sudo apt install ninja-build

          - os: windows-2019
            generator: -G "Visual Studio 16 2019" -A x64
            setup:

          - os: windows-2022
            generator: -G "Visual Studio 17 2022" -A x64
            setup:

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup
        run: ${{ matrix.setup }}

      - uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake ${{ matrix.generator }} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -DCMAKE_COMPILE_WARNING_AS_ERROR=${{ matrix.warning-as-errors }}

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }} -v

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C ${{ matrix.build-type }} --extra-verbose 
