name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, Debug ]
        cxx-standard: [ 11, 14, 17, 20 ]
        #os: [ ubuntu-latest, windows-2019, windwos-2022 ]
        include:
          - os: ubuntu-latest
            setup: |
              sudo apt update
              sudo apt install ninja-build

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: ${{ matrix.setup }}

      - name: Configure CMake
        run: |
          cmake -GNinja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }}

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }} -v

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest --extra-verbose

