name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, Debug ]
        cxx-standard: [ 11, 14, 17, 20 ]
        os: [ ubuntu-latest, windows-2019, windows-2022 ]
        include:
          - os: ubuntu-latest
            generator: -G Ninja
            setup: |
              sudo apt update
              sudo apt install ninja-build

          - os: windows-2019
            generator: -G "Visual Studio 16 2019" -A x64
            setup:

          - os: windows-2022
            generator: -G "Visual Studio 17 2022" -A x64
            setup:

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: ${{ matrix.setup }}

      - name: Configure CMake
        run: |
          cmake ${{ matrix.generator }} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }}

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }} -v

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest --config ${{ matrix.build-type }} --extra-verbose 

