name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#env:
  ## Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, Debug ]
        cxx-standard: [ 11, 14, 17, 20 ]
        os: [ ubuntu-latest, windows-2019, windwos-2022 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }} -v

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ctest --extra-verbose

